filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/dataingestion/dataingestion.log
    json.keys_under_root: true
    json.add_error_key: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]

setup.kibana:
  host: "kibana:5601"
