apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataingestion-deployment
  labels:
    app: dataingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataingestion
  template:
    metadata:
      labels:
        app: dataingestion
    spec:
      containers:
        - name: dataingestion
          image: dataingestion:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8094


